<a href="https://colab.research.google.com/github/LongntLe/CS4780/blob/master/Perceptron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [4]:
def perceptron(X, Y, w, threshold=300):
  X = np.array(X)
  w = np.array(w)
  steps = [w] # hold w values

  ctr = 0 # count number of updates
  misclassified = 1 # count number of misclassified items

  while misclassified > 0:
    misclassified = 0

    for i in range(len(X)):
      if np.sign(np.dot(X[i], w)) != Y[i]:
        w = w + Y[i] * X[i]
        steps.append(w)

        ctr += 1
        misclassified += 1
        break

    if ctr >= threshold:
      raise Exception('Cannot converge!')
      break

  return ctr, w, steps
  

In [5]:
X = [[1, 3], [-1, 4]]
Y = [1, -1]
w = [0, 0]

ctr, w, steps = perceptron (X, Y, w)

print ('Converged in {} steps'.format(ctr))

Converged in 5 steps


In [ ]:
steps

[array([0, 0]),
 array([1, 3]),
 array([ 2, -1]),
 array([3, 2]),
 array([ 4, -2]),
 array([5, 1])]

## Train vs Test error

We can calculate the train and test by calculating h(x,y) = sign(x^T*w) for both the train and test set.

But we also know that the algorithm converges when the train set has no error. So the error rate for the train set is always 0%. Therefore, we only need to assess the error rate for test set.